query events($query: Int) {
  events(where: { edition: $query }, orderBy: edition_DESC) {
    id
    date
    edition
    talks {
      id
      speakers {
        id
        name
        speakerPicture {
          url
          handle
        }
      }
    }
  }
}
