fragment SpeakerFields on Speaker {
  id
  name
  speakerPicture {
    url
    handle
    fileName
  }
}

fragment VenueFields on Venue {
  id
  name
  street
  region
  zip
  city
  country
  googleMapsUrl
}

fragment SponsorFields on Sponsor {
  id
  name
  website
  logo {
    height
    width
    mimeType
    url
  }
}

query home($date: DateTime) {
  events(
    orderBy: date_DESC,
    first: 1,
    where: {
      status: PUBLISHED
    }
  ) {
    status
    id
    date
    title
    meetupLink
    sponsors {
      ...SponsorFields
    }
    talks {
      id
      name
      abstract
      youtubecode
      speakers {
        ...SpeakerFields
      }
    }
    venue {
      ...VenueFields
    }
  }
  workshops(
    where:{
      dateAndTime_gte: $date,
    }
  ) {
    id
    name
    dateAndTime
    speakers {
      ...SpeakerFields
    }
  },
  sponsorsConnection  {
    edges {
      node {
        ...SponsorFields
        events {
          edition
        }
      }
    }
  }
  talks(
    orderBy: createdAt_DESC
    where: { status: PUBLISHED, youtubecode_not: null }
  ) {
    id
    speakers {
      ...SpeakerFields
    }
    name
    youtubecode
  }
  feedbacks {
    id
    quote
    speaker {
      ...SpeakerFields
    }
    sponsor {
      ...SponsorFields
    }
  }
}
