{
  events(orderBy: date_DESC, first: 1, where: { status: PUBLISHED }) {
    status
    id
    date
    title
    meetupLink
    sponsors {
      id
      name
      website
      logo {
        url
      }
    }
    talks {
      id
      name
      abstract
      youtubecode
      speakers {
        id
        name
        bio
        speakerPicture {
          url
          fileName
        }
      }
    }
    venue {
      id
      name
    }
  }
}
