fragment SpeakerFields on Speaker {
  id
  name
  speakerPicture {
    handle
    fileName
  }
}

fragment VenueFields on Venue {
  id
  name
  street
  region
  zip
  city
  country
  googleMapsUrl
}

query home {
  events(orderBy: date_DESC, first: 1, where: { status: PUBLISHED }) {
    status
    id
    date
    title
    meetupLink
    sponsors {
      id
      name
      website
      logo {
        url
      }
    }
    talks {
      id
      name
      abstract
      youtubecode
      speakers {
        ...SpeakerFields
      }
    }
    venue {
      ...VenueFields
    }
  }
  talks(
    orderBy: createdAt_DESC
    where: { status: PUBLISHED, youtubecode_not: null }
  ) {
    id
    speakers {
      ...SpeakerFields
    }
    name
    youtubecode
  }
  feedbacks {
    id
    quote
    speaker {
      ...SpeakerFields
    }
    sponsor {
      name
      logo {
        url
      }
    }
  }
}
