query events($date: Date) {
  events(orderBy: date_DESC, first: 1000, where: { date_lt: $date }) {
    id
    date
    time
    title
    eventType
    meetupLink
    streamLink
    venue {
      name
      city
      googleMapsUrl
    }
    talks {
      id
      name
      youtubecode
      category
      speakers {
        id
        name
        speakerPicture {
          url
        }
      }
    }
    sponsors {
      id
      name
      website
      logo {
        url
      }
    }
  }
  next: events(orderBy: date_ASC, first: 1, where: { date_gte: $date }) {
    date
    time
    title
    meetupLink
    venue {
      name
      city
    }
  }
}
