query events($first: Int!, $skip: Int!, $date: DateTime) {
  events(
    orderBy: date_DESC
    first: $first
    skip: $skip
    where: {
      status: PUBLISHED,
      date_lt: $date
    }
  ) {
    id
    date
    talks {
      id
      name
      abstract
      youtubecode
      speakers {
        id
        name
        speakerPicture {
          url
          handle
        }
      }
    }
    sponsors {
      id
      name
      website
      logo {
        url
      }
    }
  }
}
