query videos($skip: Int!) {
  talksConnection(where: { youtubecode_not: null }) {
    aggregate {
      count
    }
  }
  talks(
    orderBy: updatedAt_DESC
    first: 3
    skip: $skip
    where: { youtubecode_not: null }
  ) {
    id
    updatedAt
    speakers {
      id
      name
      speakerPicture {
        url
        handle
      }
    }
    name
    youtubecode
  }
}
