query speakers {
  speakers(orderBy: name_ASC, where: { status: PUBLISHED, talks_some: {} }) {
    id
    name
    speakerPicture {
      url
      handle
    }
    talks {
      id
      name
    }
  }
}
