query speakers {
  speakers(
    orderBy: name_ASC
    first: 1000
    where: { speakerPicture: { speakerPictureSpeaker_some: {} } }
  ) {
    id
    name
    speakerPicture {
      url
      handle
    }
    talks {
      id
      name
    }
  }
}
