query talk($id: ID!) {
  talks(where: { id: $id }, first: 1) {
    id
    name
    abstract
    youtubecode
    category
    createdAt
    speakers {
      id
      name
      speakerPicture {
        url
        handle
        fileName
      }
    }
    event {
      id
      date
    }
  }
}