query talks ($where: TalkWhereInput) {
  talks(
    orderBy: createdAt_DESC,
    where: $where
  ) {
    id
    name
    category
    speakers {
      id
      name
      speakerPicture {
        url
        handle
        fileName
      }
    }
  }
}
