query talks($where: TalkWhereInput) {
  talks(orderBy: createdAt_DESC, where: $where, first: 1000) {
    id
    name
    category
    speakers {
      id
      name
      speakerPicture {
        url
        handle
        fileName
      }
    }
  }
}
