query talk($id: ID!) {
  talks(where: { id: $id, status: PUBLISHED }) {
    id
    name
    abstract
    youtubecode
    speakers {
      id
      name
      speakerPicture {
        url
      }
    }
  }
}
