query workshops {
  workshops(orderBy: dateAndTime_DESC) {
    id
    name
    canceled
    description
    dateAndTime
    ticketUrl
    banner {
      url
    }
    speakers {
      id
      name
      speakerPicture {
        url
        handle
        fileName
      }
    }
  }
}
