query workshop($id: ID!) {
  workshops(
    where: {
      id: $id,
      status: PUBLISHED
    }
  ) {
    id
    canceled
    name
    description
    dateAndTime
    ticketUrl
    price
    banner {
      url
    }
    speakers {
      id
      name
      twitterHandle
      speakerPicture {
        url
        handle
        fileName
      }
    }
    venue {
      id
      name
      street
      region
      zip
      city
      country
      googleMapsUrl
    }
  }
}
